#!/bin/sh

set -e

ANDROID_HOME=/opt/android-sdk-linux
ANDROID=$ANDROID_HOME/tools/android

COMPONENTS=/var/opt/components.json

INSTALL_CMD="$ANDROID update sdk --no-ui --all --force --filter"

set -x

for component_spec in $*
do
    echo y | $INSTALL_CMD $component_spec
done
