#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

. $(dirname $0)/common.sh

#URI=$(jq '.source.uri' | tr -d '"')
#if [ -z "$URI" ] || [ 'null' == "$URI" ]
#then
#  URI=$DEFAULT_URI
#fi

set -x

[ -d $ANDROID_HOME ] || extractSdk /opt/
[ -d $ANDROID_HOME/platform-tools ] || sdkInstall platform-tools

jq -n --arg uri "$SDK_URI" '[{uri:$uri}]' >&3
