#!/bin/bash
set -euo pipefail
source $(dirname $0)/functions.sh

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=${1%/} # destination with no trailing slash
components=$(jq -r '.version.components')

if [ ! -d "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

extract_sdk $destination
sdk_install $destination $components

jq -n --arg comp $components '{version:{components:$comp}}' >&3
