#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

. $(dirname $0)/functions.sh

destination=${1%/} # destination with no trailing slash
config=$(mktemp)

cat >$config

if [ ! -d "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

extractSdk $destination

for component in $(cat "$config" | jq -r '.version.components[]?')
do
  sdkInstall $destination $component
done

cat "$config" | jq '{version:.version}' >&3
